#### 116개 파일 > 행단위로 통합하기

In [ ]:
### 최종 통합에 사용할 데이터 프레임명 : df
# 깨끗한 데이터 프레임 정의 : df = pd.DataFrame()
# 누적 추가 : df = pd.concat()

### 통합 후 파일 저장명 : rto_total.xlsx
# 총 row 수 : 6,960개

In [ ]:
"""
<지금까지 처리한 순서>
 1. 파일 읽어들이기
 2. [기준년월] 컬럼 추가
 3. [국적] 컬럼에서 [대륙] 이름 제거
 4. "인덱스" 재정의
 5. [대륙] 컬럼 추가
 6. [관광객비율(%)] 컬럼 추가
 7. [전체관광객비율(%)] 컬럼 추가
"""

In [1]:
## 폴더에서 파일명 리스트로 작성

import pandas as pd

read_file_list = []  # 처음에 빈 리스트로 설정

for i in range(2010, 2020):
    for j in range(1, 13):
        if i == 2019 and j == 9:
            break
        yearmonth = f"{i}{j:02d}"
        file_path_total = f"./files2/kto_{yearmonth}.xlsx"
        read_file_list.append(file_path_total)  # 파일 경로를 리스트에 추가

        # 엑셀 파일을 읽어오는 부분 (원하는 작업을 추가)
        # pd.read_excel(file_path_total)  # 엑셀 파일을 읽는 부분

print(read_file_list)

['./files2/kto_201001.xlsx', './files2/kto_201002.xlsx', './files2/kto_201003.xlsx', './files2/kto_201004.xlsx', './files2/kto_201005.xlsx', './files2/kto_201006.xlsx', './files2/kto_201007.xlsx', './files2/kto_201008.xlsx', './files2/kto_201009.xlsx', './files2/kto_201010.xlsx', './files2/kto_201011.xlsx', './files2/kto_201012.xlsx', './files2/kto_201101.xlsx', './files2/kto_201102.xlsx', './files2/kto_201103.xlsx', './files2/kto_201104.xlsx', './files2/kto_201105.xlsx', './files2/kto_201106.xlsx', './files2/kto_201107.xlsx', './files2/kto_201108.xlsx', './files2/kto_201109.xlsx', './files2/kto_201110.xlsx', './files2/kto_201111.xlsx', './files2/kto_201112.xlsx', './files2/kto_201201.xlsx', './files2/kto_201202.xlsx', './files2/kto_201203.xlsx', './files2/kto_201204.xlsx', './files2/kto_201205.xlsx', './files2/kto_201206.xlsx', './files2/kto_201207.xlsx', './files2/kto_201208.xlsx', './files2/kto_201209.xlsx', './files2/kto_201210.xlsx', './files2/kto_201211.xlsx', './files2/kto_201212.xlsx', './files2/kto_201301.xlsx', './files2/kto_201302.xlsx', './files2/kto_201303.xlsx', './files2/kto_201304.xlsx', './files2/kto_201305.xlsx', './files2/kto_201306.xlsx', './files2/kto_201307.xlsx', './files2/kto_201308.xlsx', './files2/kto_201309.xlsx', './files2/kto_201310.xlsx', './files2/kto_201311.xlsx', './files2/kto_201312.xlsx', './files2/kto_201401.xlsx', './files2/kto_201402.xlsx', './files2/kto_201403.xlsx', './files2/kto_201404.xlsx', './files2/kto_201405.xlsx', './files2/kto_201406.xlsx', './files2/kto_201407.xlsx', './files2/kto_201408.xlsx', './files2/kto_201409.xlsx', './files2/kto_201410.xlsx', './files2/kto_201411.xlsx', './files2/kto_201412.xlsx', './files2/kto_201501.xlsx', './files2/kto_201502.xlsx', './files2/kto_201503.xlsx', './files2/kto_201504.xlsx', './files2/kto_201505.xlsx', './files2/kto_201506.xlsx', './files2/kto_201507.xlsx', './files2/kto_201508.xlsx', './files2/kto_201509.xlsx', './files2/kto_201510.xlsx', './files2/kto_201511.xlsx', './files2/kto_201512.xlsx', './files2/kto_201601.xlsx', './files2/kto_201602.xlsx', './files2/kto_201603.xlsx', './files2/kto_201604.xlsx', './files2/kto_201605.xlsx', './files2/kto_201606.xlsx', './files2/kto_201607.xlsx', './files2/kto_201608.xlsx', './files2/kto_201609.xlsx', './files2/kto_201610.xlsx', './files2/kto_201611.xlsx', './files2/kto_201612.xlsx', './files2/kto_201701.xlsx', './files2/kto_201702.xlsx', './files2/kto_201703.xlsx', './files2/kto_201704.xlsx', './files2/kto_201705.xlsx', './files2/kto_201706.xlsx', './files2/kto_201707.xlsx', './files2/kto_201708.xlsx', './files2/kto_201709.xlsx', './files2/kto_201710.xlsx', './files2/kto_201711.xlsx', './files2/kto_201712.xlsx', './files2/kto_201801.xlsx', './files2/kto_201802.xlsx', './files2/kto_201803.xlsx', './files2/kto_201804.xlsx', './files2/kto_201805.xlsx', './files2/kto_201806.xlsx', './files2/kto_201807.xlsx', './files2/kto_201808.xlsx', './files2/kto_201809.xlsx', './files2/kto_201810.xlsx', './files2/kto_201811.xlsx', './files2/kto_201812.xlsx', './files2/kto_201901.xlsx', './files2/kto_201902.xlsx', './files2/kto_201903.xlsx', './files2/kto_201904.xlsx', './files2/kto_201905.xlsx', './files2/kto_201906.xlsx', './files2/kto_201907.xlsx', './files2/kto_201908.xlsx']

##### 테스트 1번

In [3]:
### 샘플링에 사용할 파일 : kto_201001.xlsx 파일 사용
# 데이터프레임 변수명 : kto_201901
# 샘플링 파일 읽어들이기....

file_path = read_file_list[0]

kto_201001 = pd.read_excel(file_path,
                           header=1,
                           skipfooter=4,
                           usecols="A:G")
kto_201001

         국적      관광     상용   공용  유학/연수     기타       계
0      아시아주  329131  18238  421   4339  80916  433045
1        일본  202825   1750   89    549   3971  209184
2        대만   35788     41   17     37    516   36399
3        홍콩   13874     55    0     21    595   14545
4       마카오     554      0    0      0      0     554
..      ...     ...    ...  ...    ...    ...     ...
62  아프리카 기타     349    594   25     86    296    1350
63     기타대륙      10      3    0      0      0      13
64     국적미상      10      3    0      0      0      13
65     교포소계       0      0    0      0  22537   22537
66       교포       0      0    0      0  22537   22537

[67 rows x 7 columns]

In [5]:
# 파일 읽기
file_path = read_file_list[0]

kto_201001 = pd.read_excel(file_path,
                           header=1,
                           skipfooter=4,
                           usecols="A:G")

### 기준년월 컬럼 추가하기 : 샘플 기준년월은 파일명에 있는 2010-01로 넣기
kto_201001["기준년월"] = "2010-01"

### 실제 국적만 추출하기
c = kto_201001["국적"].isin(['아시아주', '미주', '구주', '대양주', 
                             '아프리카주', '기타대륙', '교포소계'])
kto_201001_country = kto_201001[c == False]

### 눈에 보이는 인덱스 값을 순차적으로 재정의 하기
kto_201001_country_newindex = kto_201001_country.reset_index(drop=True)

### 총 국적 데이터 갯수 60개 국가
len(kto_201001_country_newindex)
### 컬럼에 추가할 대륙이름을 리스트로 생성하기
continents = ["아시아"]*25 + ["아메리카"]*5 + ["유럽"]*23 + ["오세아니아"]*3 + \
                ["아프리카"]*2 + ["기타대륙"] + ["교포"]

### "대륙" 컬럼에 위 리스트 데이터 추가하기
kto_201001_country_newindex["대륙"] = continents

### 국가별로 -> 관광을 위해 입국하는 비율 계산
kto_201001_country_newindex["관광객비율(%)"] = \
    round(kto_201001_country_newindex["관광"] / kto_201001_country_newindex["계"] * 100, 3)

### 관광 컬럼의 모든 데이터 sum하기
t_sum = kto_201001_country_newindex["관광"].sum()

### 국가별 관광 비율 계산
kto_201001_country_newindex["전체관광객비율(%)"] = \
        round(kto_201001_country_newindex["관광"] / t_sum * 100, 3)

kto_201001_country_newindex

,국적,관광,상용,공용,유학/연수,기타,계,기준년월,대륙,관광객비율(%),전체관광객비율(%)
0,일본,202825,1750,89,549,3971,209184,2010-01,아시아,96.960,50.603
1,대만,35788,41,17,37,516,36399,2010-01,아시아,98.321,8.929
2,홍콩,13874,55,0,21,595,14545,2010-01,아시아,95.387,3.461
3,마카오,554,0,0,0,0,554,2010-01,아시아,100.000,0.138
4,태국,13374,39,13,53,4335,17814,2010-01,아시아,75.076,3.337
5,말레이시아,3292,61,0,49,1157,4559,2010-01,아시아,72.209,0.821
6,필리핀,3984,219,104,87,16820,21214,2010-01,아시아,18.780,0.994
7,인도네시아,1840,327,3,65,2826,5061,2010-01,아시아,36.356,0.459
8,싱가포르,4201,120,3,27,1017,5368,2010-01,아시아,78.260,1.048
9,미얀마,630,18,54,10,3882,4594,2010-01,아시아,13.714,0.157
10,베트남,1384,284,21,150,2676,4515,2010-01,아시아,30.653,0.345
11,인도,1646,1387,7,68,2918,6026,2010-01,아시아,27.315,0.411
12,스리랑카,39,28,2,13,566,648,2010-01,아시아,6.019,0.010
13,파키스탄,70,200,1,41,402,714,2010-01,아시아,9.804,0.017
14,방글라데시,86,84,9,42,489,710,2010-01,아시아,12.113,0.021
15,캄보디아,102,22,0,25,131,280,2010-01,아시아,36.429,0.025
16,몽골,2333,234,6,197,554,3324,2010-01,아시아,70.187,0.582
17,중국,40425,11930,55,2751,36091,91252,2010-01,아시아,44.300,10.086
18,이란,69,309,0,3,217,598,2010-01,아시아,11.538,0.017
19,이스라엘,792,11,0,0,53,856,2010-01,아시아,92.523,0.198
20,터키,472,15,2,15,465,969,2010-01,아시아,48.710,0.118
21,우즈베키스탄,190,293,17,40,740,1280,2010-01,아시아,14.844,0.047
22,카자흐스탄,238,48,4,22,107,419,2010-01,아시아,56.802,0.059
23,GCC,223,134,0,18,55,430,2010-01,아시아,51.860,0.056
24,아시아 기타,700,629,14,56,333,1732,2010-01,아시아,40.416,0.175
25,미국,26943,1195,2145,135,12647,43065,2010-01,아메리카,62.564,6.722
26,캐나다,4912,96,4,21,3743,8776,2010-01,아메리카,55.971,1.225
27,멕시코,252,29,1,4,93,379,2010-01,아메리카,66.491,0.063
28,브라질,459,46,1,11,248,765,2010-01,아메리카,60.000,0.115
29,미주 기타,501,25,8,29,291,854,2010-01,아메리카,58.665,0.125
30,영국,5746,383,4,20,1368,7521,2010-01,유럽,76.399,1.434
31,독일,5838,255,24,68,1458,7643,2010-01,유럽,76.384,1.457
32,프랑스,3019,343,44,115,1145,4666,2010-01,유럽,64.702,0.753
33,네덜란드,1205,47,1,20,449,1722,2010-01,유럽,69.977,0.301
34,스웨덴,579,63,5,17,185,849,2010-01,유럽,68.198,0.144
35,스위스,512,30,0,7,77,626,2010-01,유럽,81.789,0.128
36,이탈리아,1157,40,12,12,155,1376,2010-01,유럽,84.084,0.289
37,덴마크,378,28,0,5,94,505,2010-01,유럽,74.851,0.094
38,노르웨이,517,274,0,6,149,946,2010-01,유럽,54.651,0.129
39,벨기에,322,25,1,8,104,460,2010-01,유럽,70.000,0.080
40,오스트리아,440,13,2,9,141,605,2010-01,유럽,72.727,0.110
41,스페인,542,29,11,8,108,698,2010-01,유럽,77.650,0.135
42,그리스,345,47,0,0,213,605,2010-01,유럽,57.025,0.086
43,포르투갈,256,9,0,1,44,310,2010-01,유럽,82.581,0.064
44,핀란드,376,16,0,12,131,535,2010-01,유럽,70.280,0.094
45,아일랜드,311,16,0,1,198,526,2010-01,유럽,59.125,0.078
46,우크라이나,386,29,0,6,1515,1936,2010-01,유럽,19.938,0.096
47,러시아,4861,505,15,83,5409,10873,2010-01,유럽,44.707,1.213
48,크로아티아,166,20,0,1,298,485,2010-01,유럽,34.227,0.041
49,루마니아,142,12,0,9,370,533,2010-01,유럽,26.642,0.035
50,불가리아,103,0,0,9,414,526,2010-01,유럽,19.582,0.026
51,폴란드,378,29,0,10,431,848,2010-01,유럽,44.575,0.094
52,구주 기타,1219,37,0,49,410,1715,2010-01,유럽,71.079,0.304
53,오스트레일리아,6974,340,9,10,1098,8431,2010-01,오세아니아,82.719,1.740
54,뉴질랜드,1545,53,1,1,435,2035,2010-01,오세아니아,75.921,0.385
55,대양주 기타,730,0,4,4,168,906,2010-01,오세아니아,80.574,0.182
56,남아프리카공화국,214,27,0,2,545,788,2010-01,아프리카,27.157,0.053
57,아프리카 기타,349,594,25,86,296,1350,2010-01,아프리카,25.852,0.087
58,국적미상,10,3,0,0,0,13,2010-01,기타대륙,76.923,0.002
59,교포,0,0,0,0,22537,22537,2010-01,교포,0.000,0.000

In [8]:
import pandas as pd

# 통합할 데이터프레임 정의
df = pd.DataFrame()

# 파일 경로 리스트 작성
read_file_list = []  # 파일 경로를 담을 리스트

for y in range(2010, 2020):
    for m in range(1, 13):
        if y == 2019 and m == 9:
            break
        yearmonth = f"{y}{m:02d}"
        file_path_total = f"./files2/kto_{yearmonth}.xlsx"
        read_file_list.append(file_path_total)  # 파일 경로를 리스트에 추가

# 대륙 리스트 정의
continents = ["아시아"]*25 + ["아메리카"]*5 + ["유럽"]*23 + ["오세아니아"]*3 + \
                ["아프리카"]*2 + ["기타대륙"] + ["교포"]

# 파일 읽고 처리한 후, df에 누적 추가하는 과정
for file_path in read_file_list:
    # 파일 읽기
    kto_data = pd.read_excel(file_path,
                             header=1,
                             skipfooter=4,
                             usecols="A:G")

    # 기준년월 컬럼 추가하기
    yearmonth = file_path.split('_')[-1].split('.')[0]  # 파일명에서 연월 추출
    kto_data["기준년월"] = f"{yearmonth[:4]}-{yearmonth[4:]}"
    
    # 실제 국적만 추출하기
    c = kto_data["국적"].isin(['아시아주', '미주', '구주', '대양주', '아프리카주', '기타대륙', '교포소계'])
    kto_data_country = kto_data[c == False]
    
    # 인덱스 재정의
    kto_data_country_newindex = kto_data_country.reset_index(drop=True)
    
    # 대륙 컬럼 추가
    kto_data_country_newindex["대륙"] = continents
    
    # 관광객비율(%) 컬럼 추가
    kto_data_country_newindex["관광객비율(%)"] = round(kto_data_country_newindex["관광"] / kto_data_country_newindex["계"] * 100, 3)
    
    # 전체 관광객비율(%) 계산
    total_tourism_sum = kto_data_country_newindex["관광"].sum()
    kto_data_country_newindex["전체관광객비율(%)"] = round(kto_data_country_newindex["관광"] / total_tourism_sum * 100, 3)

    # 각 파일의 데이터를 df에 누적 추가
    df = pd.concat([df, kto_data_country_newindex], ignore_index=True)

# 통합된 데이터프레임을 엑셀 파일로 저장
df.to_excel("rto_total.xlsx", index=False)